name: Create Zip Archives

on: [workflow_dispatch, push]

jobs:
  create-zips:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Run process
      run: |
        pip install -q pandas requests
        python -W ignore download_zips.py
    
    - name: Delete previous 'latest' release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        delete_release: true
        tag_name: "latest"
        github_token: ${{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}}
      continue-on-error: true
    
    - name: Create new release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        name: "Zip Files"
        body: |
          https://github.com/${{ github.repository }}/releases/latest/download/PRIMARY.zip
          https://github.com/${{ github.repository }}/releases/latest/download/Secondary_Higher_Secondary.zip
          
          $(TZ="Asia/Kolkata" date '+%d-%b-%Y %H:%M IST')
        files: |
          PRIMARY.zip
          Secondary_Higher_Secondary.zip
