name: My Watch List

on:
  schedule:
    - cron: '*/15 2-8 * * 1-5'
  workflow_dispatch:
    inputs:  # Add this section
      triggered_by:
        description: 'Who triggered this workflow'
        required: false
        default: 'manual'
      timestamp:
        description: 'Trigger timestamp'
        required: false

jobs:
  update-csv:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with CACHE
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Uses cached packages

      - name: Run both scripts
        run: |
          python Scripts/fetch_and_save.py
          python Scripts/nifty50_top10.py
          python Scripts/etf_fetch.py
          python Scripts/global_data.py
          python Scripts/global_commodity.py
          python Scripts/eco.py
          python Scripts/cash.py
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Data/nse_all_indices.csv Data/nifty50_stocks_top10.csv Data/etf.csv Data/GLOBAL_DATA.csv Data/GLOBAL_COMMODITIES.csv Data/Economic.csv Data/Cash.csv
          git commit -m "Auto update $(date)" || exit 0
          git push
