name: Daily Option Chain Update

on:
  schedule:
    - cron: '30 0 * * 1-6'    # 06:30 IST
    - cron: '30 3 * * 1-6'    # 09:30 IST
    - cron: '30 6 * * 1-6'    # 12:30 IST
    - cron: '30 9 * * 1-6'    # 15:30 IST
    - cron: '30 12 * * 1-6'   # 18:30 IST
    - cron: '30 15 * * 1-6'   # 21:30 IST
    - cron: '30 18 * * 1-5'   # 00:30 IST (Next day)
  workflow_dispatch:

jobs:
  update-option-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Option Chain script
        run: python Scripts/nifty_options.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Data/Option.csv
          git commit -m "Auto update Option Chain $(date)" || exit 0
          git push
